### PR TITLE
translation Japanese

### PR DESCRIPTION
**Pull request by ghost**
I try translation Japanese and it works for me.
but "multibite-page-title" acting weird sometime. 
it seems better to use rawurlencode, could you tell me where to use it?

### CODE REVIEW

**Comment by remijean** [comment]
@Cahell thanks you !

The function rawurlencode should be added to the file core/core.php line 1345 : 

```
case self::FILTER_ID:
	$text = rawurlencode(preg_replace('/([^a-z0-9!#$%&\'*+-=?^`{|}~@.\[\]])/', '', str_replace(explode(',', $search), explode(',', $replace), mb_strtolower($text, 'UTF-8'))));
	break;
```

**Comment by ghost** [comment]
Thank you too Rémi.
it works with removing preg_replace rather than using rawurlencode.
I am going to find another way.

			case self::FILTER_ID:
				$text = str_replace(explode(',', $search), explode(',', $replace), mb_strtolower($text, 'UTF-8'));
				break;

**Comment by ghost** [comment]
Finally, I found it.

			case self::FILTER_ID:
				$text = preg_replace('/([!#$%&\'*+-=?^`{|}~@.\[\]])/', '', str_replace(explode(',', $search), explode(',', $replace), mb_strtolower($text, 'UTF-8')));
				break;

This could work perfectly for me now, I hope not to go wrong with this code.

**Comment by remijean** [comment]
4 years later... :roll_eyes: this repository is unmaintained, new repository: https://forge.chapril.org/ZwiiCMS-Team/ZwiiCMS

**Pull request closed without merging**
